import { CITATIONS, NIST_TIMELINE } from "./crypto-registry";
import { ENGINE_VERSION } from "./engine";
import { SEAL_ALGORITHM } from "./seal";
import type { Survey } from "./types";
import { site } from "@/config/site";

/**
 * The takeaway artifact: a migration plan a security lead can paste into a
 * review. Every claim carries the source and the seal it was computed under, so
 * the document stands on its own after the browser tab is gone.
 */

export type ExportFormat = "md" | "json" | "csv";

export function buildJson(survey: Survey): string {
  return `${JSON.stringify(
    {
      product: site.name,
      engineVersion: survey.analysis?.engineVersion ?? ENGINE_VERSION,
      sealAlgorithm: SEAL_ALGORITHM,
      exportedAt: new Date().toISOString(),
      survey: {
        id: survey.id,
        name: survey.name,
        repoHint: survey.repoHint,
        ecosystem: survey.ecosystem,
        horizonYear: survey.horizonYear,
        shared: survey.shared,
        createdAt: survey.createdAt,
        genesisSeal: survey.genesisSeal,
        headSeal: survey.lastSeal,
        eventCount: survey.eventCount,
      },
      analysis: survey.analysis,
      surfaces: survey.surfaces.map((surface) => {
        const assessment = survey.analysis?.surfaces.find((entry) => entry.surfaceId === surface.id);
        return {
          id: surface.id,
          label: surface.label,
          family: surface.family,
          primitive: surface.primitive,
          usage: surface.usage,
          location: surface.location,
          evidence: surface.evidence,
          shelfLifeYears: surface.shelfLifeYears,
          decision: surface.decision,
          decisionNote: surface.decisionNote,
          enrichment: surface.enrichment,
          assessment,
        };
      }),
      citations: CITATIONS,
    },
    null,
    2,
  )}\n`;
}

function csvCell(value: unknown): string {
  const text = value === null || value === undefined ? "" : String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function buildCsv(survey: Survey): string {
  const header = [
    "surface",
    "primitive",
    "family",
    "usage",
    "key_bits",
    "shelf_life_years",
    "quantum_bits",
    "score",
    "band",
    "residual_score",
    "must_start_by",
    "decryptable_from",
    "decrypt_window_years",
    "replacement",
    "replacement_standard",
    "decision",
    "decision_note",
    "location",
    "evidence",
  ];
  const rows = survey.surfaces.map((surface) => {
    const assessment = survey.analysis?.surfaces.find((entry) => entry.surfaceId === surface.id);
    return [
      surface.label,
      surface.primitive,
      surface.family,
      surface.usage,
      surface.keyBits ?? "",
      surface.shelfLifeYears,
      assessment?.quantumBits ?? "",
      assessment?.score ?? "",
      assessment?.band ?? "",
      assessment?.residualScore ?? "",
      assessment?.mustStartBy ?? "",
      assessment?.decryptableFrom ?? "",
      assessment?.decryptWindowYears ?? "",
      assessment?.replacement.primitive ?? "",
      assessment?.replacement.standard ?? "",
      surface.decision,
      surface.decisionNote,
      surface.location,
      surface.evidence,
    ].map(csvCell);
  });
  return [header.map(csvCell).join(","), ...rows].join("\n") + "\n";
}

export function buildMarkdown(survey: Survey): string {
  const analysis = survey.analysis;
  const live = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push(`# ${survey.name} \u2014 post-quantum migration plan`);
  lines.push("");
  lines.push(`> Generated by ${site.name} ${site.version} \u00b7 engine \`${analysis?.engineVersion ?? ENGINE_VERSION}\` \u00b7 ${live}`);
  lines.push("");
  lines.push(
    "This plan is an engineering aid, not an assurance. Every number below is produced by a deterministic function you can read and re-run; none of it is a certification, and it does not tell you whether a specific system is safe.",
  );
  lines.push("");

  lines.push("## Deadline arithmetic");
  lines.push("");
  lines.push(
    "Mosca's rule: if data must stay confidential for **X** years after capture, the migration takes **Y** years, and a cryptographically relevant quantum computer arrives in **H**, work must start by **H \u2212 (X + Y)**.",
  );
  lines.push("");
  lines.push("| Setting | Value | Source |");
  lines.push("| --- | --- | --- |");
  lines.push(`| Quantum-capability horizon (H) | ${survey.horizonYear} | Analyst assumption, editable in Settings |`);
  lines.push(`| NIST deprecates 112-bit public key | ${NIST_TIMELINE.deprecateBy} | [NIST IR 8547](${CITATIONS.nistIr8547.href}) |`);
  lines.push(`| NIST disallows quantum-vulnerable public key | ${NIST_TIMELINE.disallowFrom} | [NIST IR 8547](${CITATIONS.nistIr8547.href}) |`);
  lines.push(`| NIST disallows 112-bit-level symmetric | ${NIST_TIMELINE.symmetricFloorDisallowFrom} | [NIST IR 8547](${CITATIONS.nistIr8547.href}) |`);
  lines.push("");

  lines.push("## Portfolio");
  lines.push("");
  if (!analysis || analysis.surfaceCount === 0) {
    lines.push("Nothing was discovered, so there is nothing to migrate yet. Import a manifest or a source excerpt first.");
  } else {
    lines.push(`- **Weighted exposure score:** ${analysis.score} / 100 (${analysis.band})`);
    lines.push(`- **After the recorded decisions:** ${analysis.residualScore} / 100 (${analysis.residualBand})`);
    lines.push(`- **Surfaces:** ${analysis.surfaceCount}, of which ${analysis.triagedCount} triaged and ${analysis.overdueCount} already past their start date`);
    lines.push(`- **First thing that breaks:** in ${analysis.exposureYears} years`);
    if (analysis.weakestSurface) {
      lines.push(`- **Highest risk:** ${analysis.weakestSurface.label} at ${analysis.weakestSurface.score}`);
    }
  }
  lines.push("");

  lines.push("## Surfaces");
  lines.push("");
  lines.push("| Surface | Primitive | Role | X (yrs) | Score | Start by | Decryptable from | Replacement | Decision |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const surface of survey.surfaces) {
    const assessment = analysis?.surfaces.find((entry) => entry.surfaceId === surface.id);
    lines.push(
      `| ${surface.label.replace(/\|/g, "/")} | ${surface.primitive} | ${surface.usage} | ${surface.shelfLifeYears} | ${assessment?.score ?? "-"} | ${assessment?.mustStartBy ?? "-"} | ${assessment?.decryptableFrom ?? "-"} | ${assessment?.replacement.primitive.replace(/\|/g, "/") ?? "-"} | ${surface.decision}${surface.decisionNote ? ` \u2014 ${surface.decisionNote.replace(/\|/g, "/")}` : ""} |`,
    );
  }
  lines.push("");

  lines.push("## Why each score is what it is");
  lines.push("");
  for (const surface of survey.surfaces.slice(0, 40)) {
    const assessment = analysis?.surfaces.find((entry) => entry.surfaceId === surface.id);
    if (!assessment) continue;
    lines.push(`### ${surface.label}`);
    lines.push("");
    lines.push(`${assessment.headline}`);
    lines.push("");
    lines.push(`Quantum strength: **${assessment.quantumBits} bits**. ${assessment.resource.citation}.`);
    lines.push("");
    lines.push("| Factor | Weight | Severity | Points | Why |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const factor of assessment.factors) {
      lines.push(
        `| ${factor.label} | ${factor.weight.toFixed(2)} | ${factor.severity.toFixed(2)} | ${factor.contribution.toFixed(1)} | ${factor.detail.replace(/\|/g, "/")} _${factor.evidence.replace(/\|/g, "/")}_ |`,
      );
    }
    lines.push("");
  }

  lines.push("## Live data provenance");
  lines.push("");
  const enriched = survey.surfaces.filter((surface) => surface.enrichment.latestVersion || surface.enrichment.advisoryCount);
  if (enriched.length === 0) {
    lines.push("No dependency resolved a live release record, so the supply factor was treated as unknown rather than invented.");
  } else {
    lines.push("| Dependency | Latest release | Published | License | Advisories | deps.dev | OSV |");
    lines.push("| --- | --- | --- | --- | --- | --- | --- |");
    for (const surface of enriched) {
      const e = surface.enrichment;
      lines.push(
        `| ${surface.packageName ?? surface.label} | ${e.latestVersion ?? "-"} | ${e.latestVersionPublishedAt ? e.latestVersionPublishedAt.slice(0, 10) : "-"} | ${e.license ?? "-"} | ${e.advisoryCount} | ${e.depsDevStatus} | ${e.osvStatus} |`,
      );
    }
  }
  lines.push("");
  lines.push("Sources: [deps.dev](https://deps.dev), [OSV](https://osv.dev), [arXiv quant-ph / cs.CR](https://arxiv.org), [NIST news](https://www.nist.gov/news-events/news).");
  lines.push("");

  lines.push("## Integrity");
  lines.push("");
  lines.push(`- Seal algorithm: \`${SEAL_ALGORITHM}\`, \`seal_n = SHA-384(UTF-8(prevSeal) || canonicalJson(event_n))\``);
  lines.push(`- Genesis seal: \`${survey.genesisSeal}\``);
  lines.push(`- Head seal: \`${survey.lastSeal}\` over ${survey.eventCount} event(s)`);
  lines.push(`- Replay from this export: \`GET ${site.apiUrl}/integrity?survey=${survey.id}\``);
  lines.push(`- Source: ${site.repoUrl}`);
  lines.push("");

  lines.push("## Sources for the numbers");
  lines.push("");
  for (const citation of Object.values(CITATIONS)) {
    lines.push(`- ${citation.label} \u2014 ${citation.href}`);
  }
  lines.push("");

  return lines.join("\n");
}

export function buildExport(survey: Survey, format: ExportFormat): { body: string; contentType: string; filename: string } {
  const slug = survey.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "survey";
  switch (format) {
    case "json":
      return { body: buildJson(survey), contentType: "application/json; charset=utf-8", filename: `${slug}-migration-plan.json` };
    case "csv":
      return { body: buildCsv(survey), contentType: "text/csv; charset=utf-8", filename: `${slug}-migration-plan.csv` };
    default:
      return { body: buildMarkdown(survey), contentType: "text/markdown; charset=utf-8", filename: `${slug}-migration-plan.md` };
  }
}