import { getDb, type SqlExecutor } from "./client";

/**
 * Idempotent schema creation. Every statement is `IF NOT EXISTS`, so the first
 * request against a fresh database builds the whole thing and later requests
 * are a no-op. Timestamps are stored as ISO-8601 text generated by the
 * application rather than by the database, which keeps the seal chain
 * byte-identical across the hosted and embedded adapters.
 */

const STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS sessions (
     id text PRIMARY KEY,
     created_at text NOT NULL,
     last_seen_at text NOT NULL
   )`,

  `CREATE TABLE IF NOT EXISTS surveys (
     id uuid PRIMARY KEY,
     session_id text NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
     name text NOT NULL,
     repo_hint text NOT NULL DEFAULT '',
     ecosystem text,
     horizon_year integer NOT NULL,
     shared integer NOT NULL DEFAULT 0,
     status text NOT NULL DEFAULT 'active',
     created_at text NOT NULL,
     updated_at text NOT NULL,
     deleted_at text,
     genesis_seal text NOT NULL,
     last_seal text NOT NULL,
     event_count integer NOT NULL DEFAULT 0
   )`,

  `CREATE INDEX IF NOT EXISTS surveys_session_idx ON surveys (session_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS surveys_shared_idx ON surveys (id) WHERE shared = 1`,

  `CREATE TABLE IF NOT EXISTS surfaces (
     id uuid PRIMARY KEY,
     survey_id uuid NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
     label text NOT NULL,
     family text NOT NULL,
     primitive text NOT NULL,
     key_bits integer,
     usage text NOT NULL DEFAULT 'unknown',
     origin text NOT NULL,
     ecosystem text,
     package_name text,
     package_version text,
     location text NOT NULL DEFAULT '',
     evidence text NOT NULL DEFAULT '',
     shelf_life_years integer NOT NULL DEFAULT 5,
     decision text NOT NULL DEFAULT 'untriaged',
     decision_note text NOT NULL DEFAULT '',
     decided_at text,
     family_from_model integer NOT NULL DEFAULT 0,
     model_confidence double precision,
     enrichment text,
     created_at text NOT NULL,
     updated_at text NOT NULL,
     deleted_at text
   )`,

  `CREATE INDEX IF NOT EXISTS surfaces_survey_idx ON surfaces (survey_id, created_at ASC)`,
  `CREATE INDEX IF NOT EXISTS surfaces_decision_idx ON surfaces (survey_id, decision)`,

  `CREATE TABLE IF NOT EXISTS audit_events (
     survey_id uuid NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
     seq integer NOT NULL,
     type text NOT NULL,
     at text NOT NULL,
     payload text NOT NULL,
     prev_seal text NOT NULL,
     seal text NOT NULL,
     surface_id uuid,
     PRIMARY KEY (survey_id, seq)
   )`,

  `CREATE TABLE IF NOT EXISTS settings (
     session_id text PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
     horizon_year integer NOT NULL,
     critical_threshold integer NOT NULL,
     high_threshold integer NOT NULL,
     lead_time_years double precision NOT NULL,
     updated_at text NOT NULL
   )`,

  `CREATE TABLE IF NOT EXISTS classifier_feedback (
     id serial PRIMARY KEY,
     session_id text NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
     text text NOT NULL,
     label text NOT NULL,
     created_at text NOT NULL
   )`,

  `CREATE INDEX IF NOT EXISTS classifier_feedback_session_idx ON classifier_feedback (session_id, id)`,

  `CREATE TABLE IF NOT EXISTS idempotency_keys (
     key text PRIMARY KEY,
     session_id text NOT NULL,
     scope text NOT NULL,
     response text NOT NULL,
     created_at text NOT NULL
   )`,

  // Additive migrations. `CREATE TABLE IF NOT EXISTS` will not add a column to
  // a table that already exists, so a local database created by an earlier
  // version needs these explicitly.
  `ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS surface_id uuid`,
  `ALTER TABLE surfaces ADD COLUMN IF NOT EXISTS family_from_model integer NOT NULL DEFAULT 0`,
  `ALTER TABLE surfaces ADD COLUMN IF NOT EXISTS model_confidence double precision`,
  `ALTER TABLE surfaces ADD COLUMN IF NOT EXISTS enrichment text`,
];

let schemaPromise: Promise<void> | null = null;

export async function ensureSchema(db?: SqlExecutor): Promise<void> {
  if (!db) {
    if (!schemaPromise) {
      schemaPromise = getDb().then(async (executor) => {
        for (const statement of STATEMENTS) {
          await executor.query(statement);
        }
      });
    }
    await schemaPromise;
    return;
  }
  for (const statement of STATEMENTS) {
    await db.query(statement);
  }
}

/** Test hook: allow a fresh suite to rebuild the schema. */
export function resetSchemaCache(): void {
  schemaPromise = null;
}